/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.gendsl.tests

import com.google.inject.Inject
import gENdsl.GenealogyTree
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(GenDslInjectorProvider)
class GenDslParsingTest{

	@Inject
	ParseHelper<GenealogyTree> parseHelper

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}

}
