/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.gendsl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.gendsl.ui.internal.GendslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class GenDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return GendslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return GendslActivator.getInstance().getInjector(GendslActivator.ORG_XTEXT_EXAMPLE_GENDSL_GENDSL);
	}
	
}
