/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.gendsl.validation;

import org.xtext.example.gendsl.validation.AbstractGenDslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class GenDslValidator extends AbstractGenDslValidator {
}
