<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="gENdsl" nsURI="http://www.example.org/gENdsl" nsPrefix="gENdsl">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="GenealogyTree">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="familyName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="established" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="person" upperBound="-1"
        eType="#//Person" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cohabitation" upperBound="-1"
        eType="#//Cohabitation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="marriage" upperBound="-1"
        eType="#//Marriage" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Marriage">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="min2Spouses parentsOlder"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="min2Spouses" value="spouses->size() >= 1"/>
      <details key="parentsOlder" value="spouses->forAll(s | children->forAll(c | &#xA;&#x9;&#x9;&#x9;&#x9;(not c.oclIsUndefined() and not s.oclIsUndefined()) &#xA;&#x9;&#x9;&#x9;&#x9;implies (c.birthDate > s.birthDate)&#xA;&#x9;&#x9;))"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fromDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="toDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="spouses" upperBound="-1"
        eType="#//Person" eOpposite="#//Person/marriages"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//TypeOfIntimateRelationship"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Person" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cohabitation">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="min2Partners parentsOlder"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="min2Partners" value="partners->size() >= 1"/>
      <details key="parentsOlder" value="partners->forAll(s | children->forAll(c | &#xA;&#x9;&#x9;&#x9;&#x9;(not c.oclIsUndefined() and not s.oclIsUndefined()) &#xA;&#x9;&#x9;&#x9;&#x9;implies (c.birthDate > s.birthDate)&#xA;&#x9;&#x9;))"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fromDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="toDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//TypeOfIntimateRelationship"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="partners" upperBound="-1"
        eType="#//Person" eOpposite="#//Person/cohabitations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Person" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Person">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="leastOneMarriageOrCohabitation"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="leastOneMarriageOrCohabitation" value="(type = TypeOfPerson::MARRIED) implies (marriages->size() + cohabitations->size() >= 1)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="givenName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="birthDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deathDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="birthPlace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deathPlace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="restingPlace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//TypeOfPerson"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gender" eType="#//Gender"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="otherNames" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nickname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="marriages" upperBound="-1"
        eType="#//Marriage" eOpposite="#//Marriage/spouses"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cohabitations" upperBound="-1"
        eType="#//Cohabitation" eOpposite="#//Cohabitation/partners"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deathCause" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="personhistory" upperBound="-1"
        eType="#//PersonHistory" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cohabitation" upperBound="-1"
        eType="#//Cohabitation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="marriage" upperBound="-1"
        eType="#//Marriage" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TypeOfPerson">
    <eLiterals name="BIOLOGICAL"/>
    <eLiterals name="ADOPTED" value="1"/>
    <eLiterals name="SEMIADOPTED" value="2"/>
    <eLiterals name="MARRIED" value="3"/>
    <eLiterals name="DISOWNED" value="4"/>
    <eLiterals name="ILLEGITIMATE" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Gender">
    <eLiterals name="MALE"/>
    <eLiterals name="FEMALE" value="1"/>
    <eLiterals name="BIGENDER" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TypeOfIntimateRelationship">
    <eLiterals name="MONOGAMY"/>
    <eLiterals name="POLYGAMY" value="1"/>
    <eLiterals name="POLYFIDELITY" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PersonHistory">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gender" eType="#//Gender"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="givenName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
</ecore:EPackage>
