/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.gendsl.serializer;

import com.google.inject.Inject;
import gENdsl.Cohabitation;
import gENdsl.DateX;
import gENdsl.GENdslPackage;
import gENdsl.GenealogyTree;
import gENdsl.Marriage;
import gENdsl.Person;
import gENdsl.PersonHistory;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.xtext.example.gendsl.services.GenDslGrammarAccess;

@SuppressWarnings("all")
public class GenDslSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private GenDslGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == GENdslPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case GENdslPackage.COHABITATION:
				sequence_Cohabitation(context, (Cohabitation) semanticObject); 
				return; 
			case GENdslPackage.DATE_X:
				sequence_DateX(context, (DateX) semanticObject); 
				return; 
			case GENdslPackage.GENEALOGY_TREE:
				sequence_GenealogyTree(context, (GenealogyTree) semanticObject); 
				return; 
			case GENdslPackage.MARRIAGE:
				sequence_Marriage(context, (Marriage) semanticObject); 
				return; 
			case GENdslPackage.PERSON:
				sequence_Person(context, (Person) semanticObject); 
				return; 
			case GENdslPackage.PERSON_HISTORY:
				sequence_PersonHistory(context, (PersonHistory) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     Cohabitation returns Cohabitation
	 *
	 * Constraint:
	 *     (
	 *         legitimate?='legitimate'? 
	 *         type=TypeOfIntimateRelationship? 
	 *         (partners+=[Person|EString] partners+=[Person|EString]*)? 
	 *         (children+=Person children+=Person*)?
	 *     )
	 */
	protected void sequence_Cohabitation(ISerializationContext context, Cohabitation semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     DateX returns DateX
	 *
	 * Constraint:
	 *     (year=EIntegerObject? month=EIntegerObject? day=EIntegerObject?)
	 */
	protected void sequence_DateX(ISerializationContext context, DateX semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     GenealogyTree returns GenealogyTree
	 *
	 * Constraint:
	 *     (familyName=EString established=DateX? (person+=Person person+=Person*)?)
	 */
	protected void sequence_GenealogyTree(ISerializationContext context, GenealogyTree semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Marriage returns Marriage
	 *
	 * Constraint:
	 *     (
	 *         type=TypeOfIntimateRelationship? 
	 *         (spouses+=[Person|EString] spouses+=[Person|EString]*)? 
	 *         fromDate=DateX? 
	 *         toDate=DateX? 
	 *         (children+=Person children+=Person*)?
	 *     )
	 */
	protected void sequence_Marriage(ISerializationContext context, Marriage semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     PersonHistory returns PersonHistory
	 *
	 * Constraint:
	 *     (gender=Gender? givenName=EString? changed=EDate?)
	 */
	protected void sequence_PersonHistory(ISerializationContext context, PersonHistory semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Person returns Person
	 *
	 * Constraint:
	 *     (
	 *         unknown=EBoolean 
	 *         givenName=EString? 
	 *         birthPlace=EString? 
	 *         deathPlace=EString? 
	 *         restingPlace=EString? 
	 *         type=TypeOfPerson? 
	 *         gender=Gender? 
	 *         (otherNames+=EString otherNames+=EString*)? 
	 *         nickname=EString? 
	 *         deathCause=EString? 
	 *         (marriages+=[Marriage|EString] marriages+=[Marriage|EString]*)? 
	 *         (cohabitations+=[Cohabitation|EString] cohabitations+=[Cohabitation|EString]*)? 
	 *         birthDate=DateX? 
	 *         deathDate=DateX? 
	 *         (personhistory+=PersonHistory personhistory+=PersonHistory*)? 
	 *         (cohabitation+=Cohabitation cohabitation+=Cohabitation*)? 
	 *         (marriage+=Marriage marriage+=Marriage*)?
	 *     )
	 */
	protected void sequence_Person(ISerializationContext context, Person semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
