/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.gendsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractEnumRuleElementFinder;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class GenDslGrammarAccess extends AbstractGrammarElementFinder {
	
	public class GenealogyTreeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.gendsl.GenDsl.GenealogyTree");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cGenealogyTreeKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cFamilyNameKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cFamilyNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cFamilyNameEStringParserRuleCall_3_0 = (RuleCall)cFamilyNameAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cEstablishedKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cEstablishedAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cEstablishedDateXParserRuleCall_4_1_0 = (RuleCall)cEstablishedAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cPersonKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cPersonAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cPersonPersonParserRuleCall_5_2_0 = (RuleCall)cPersonAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cPersonAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cPersonPersonParserRuleCall_5_3_1_0 = (RuleCall)cPersonAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//GenealogyTree:
		//	'GenealogyTree'
		//	'{'
		//	'familyName' familyName=EString ('established' established=DateX)? ('person' '{' person+=Person ("," person+=Person)*
		//	'}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'GenealogyTree' '{' 'familyName' familyName=EString ('established' established=DateX)? ('person' '{' person+=Person (","
		//person+=Person)* '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//'GenealogyTree'
		public Keyword getGenealogyTreeKeyword_0() { return cGenealogyTreeKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'familyName'
		public Keyword getFamilyNameKeyword_2() { return cFamilyNameKeyword_2; }
		
		//familyName=EString
		public Assignment getFamilyNameAssignment_3() { return cFamilyNameAssignment_3; }
		
		//EString
		public RuleCall getFamilyNameEStringParserRuleCall_3_0() { return cFamilyNameEStringParserRuleCall_3_0; }
		
		//('established' established=DateX)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'established'
		public Keyword getEstablishedKeyword_4_0() { return cEstablishedKeyword_4_0; }
		
		//established=DateX
		public Assignment getEstablishedAssignment_4_1() { return cEstablishedAssignment_4_1; }
		
		//DateX
		public RuleCall getEstablishedDateXParserRuleCall_4_1_0() { return cEstablishedDateXParserRuleCall_4_1_0; }
		
		//('person' '{' person+=Person ("," person+=Person)* '}')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'person'
		public Keyword getPersonKeyword_5_0() { return cPersonKeyword_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }
		
		//person+=Person
		public Assignment getPersonAssignment_5_2() { return cPersonAssignment_5_2; }
		
		//Person
		public RuleCall getPersonPersonParserRuleCall_5_2_0() { return cPersonPersonParserRuleCall_5_2_0; }
		
		//("," person+=Person)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//person+=Person
		public Assignment getPersonAssignment_5_3_1() { return cPersonAssignment_5_3_1; }
		
		//Person
		public RuleCall getPersonPersonParserRuleCall_5_3_1_0() { return cPersonPersonParserRuleCall_5_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.gendsl.GenDsl.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class DateXElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.gendsl.GenDsl.DateX");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cDateXAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cDateXKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cYearKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cYearAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cYearEIntegerObjectParserRuleCall_3_1_0 = (RuleCall)cYearAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cMonthKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cMonthAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cMonthEIntegerObjectParserRuleCall_4_1_0 = (RuleCall)cMonthAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cDayKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cDayAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cDayEIntegerObjectParserRuleCall_5_1_0 = (RuleCall)cDayAssignment_5_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//DateX:
		//	{DateX}
		//	'DateX'
		//	'{' ('year' year=EIntegerObject)? ('month' month=EIntegerObject)? ('day' day=EIntegerObject)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{DateX} 'DateX' '{' ('year' year=EIntegerObject)? ('month' month=EIntegerObject)? ('day' day=EIntegerObject)? '}'
		public Group getGroup() { return cGroup; }
		
		//{DateX}
		public Action getDateXAction_0() { return cDateXAction_0; }
		
		//'DateX'
		public Keyword getDateXKeyword_1() { return cDateXKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('year' year=EIntegerObject)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'year'
		public Keyword getYearKeyword_3_0() { return cYearKeyword_3_0; }
		
		//year=EIntegerObject
		public Assignment getYearAssignment_3_1() { return cYearAssignment_3_1; }
		
		//EIntegerObject
		public RuleCall getYearEIntegerObjectParserRuleCall_3_1_0() { return cYearEIntegerObjectParserRuleCall_3_1_0; }
		
		//('month' month=EIntegerObject)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'month'
		public Keyword getMonthKeyword_4_0() { return cMonthKeyword_4_0; }
		
		//month=EIntegerObject
		public Assignment getMonthAssignment_4_1() { return cMonthAssignment_4_1; }
		
		//EIntegerObject
		public RuleCall getMonthEIntegerObjectParserRuleCall_4_1_0() { return cMonthEIntegerObjectParserRuleCall_4_1_0; }
		
		//('day' day=EIntegerObject)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'day'
		public Keyword getDayKeyword_5_0() { return cDayKeyword_5_0; }
		
		//day=EIntegerObject
		public Assignment getDayAssignment_5_1() { return cDayAssignment_5_1; }
		
		//EIntegerObject
		public RuleCall getDayEIntegerObjectParserRuleCall_5_1_0() { return cDayEIntegerObjectParserRuleCall_5_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class PersonElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.gendsl.GenDsl.Person");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPersonKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cUnknownKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cUnknownAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cUnknownEBooleanParserRuleCall_2_1_0 = (RuleCall)cUnknownAssignment_2_1.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cGivenNameKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cGivenNameAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cGivenNameEStringParserRuleCall_3_1_0 = (RuleCall)cGivenNameAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cBirthPlaceKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cBirthPlaceAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cBirthPlaceEStringParserRuleCall_4_1_0 = (RuleCall)cBirthPlaceAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cDeathPlaceKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cDeathPlaceAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cDeathPlaceEStringParserRuleCall_5_1_0 = (RuleCall)cDeathPlaceAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cRestingPlaceKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cRestingPlaceAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cRestingPlaceEStringParserRuleCall_6_1_0 = (RuleCall)cRestingPlaceAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cTypeKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cTypeAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cTypeTypeOfPersonEnumRuleCall_7_1_0 = (RuleCall)cTypeAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cGenderKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cGenderAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cGenderGenderEnumRuleCall_8_1_0 = (RuleCall)cGenderAssignment_8_1.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cOtherNamesKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_9_1 = (Keyword)cGroup_9.eContents().get(1);
		private final Assignment cOtherNamesAssignment_9_2 = (Assignment)cGroup_9.eContents().get(2);
		private final RuleCall cOtherNamesEStringParserRuleCall_9_2_0 = (RuleCall)cOtherNamesAssignment_9_2.eContents().get(0);
		private final Group cGroup_9_3 = (Group)cGroup_9.eContents().get(3);
		private final Keyword cCommaKeyword_9_3_0 = (Keyword)cGroup_9_3.eContents().get(0);
		private final Assignment cOtherNamesAssignment_9_3_1 = (Assignment)cGroup_9_3.eContents().get(1);
		private final RuleCall cOtherNamesEStringParserRuleCall_9_3_1_0 = (RuleCall)cOtherNamesAssignment_9_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9_4 = (Keyword)cGroup_9.eContents().get(4);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cNicknameKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cNicknameAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final RuleCall cNicknameEStringParserRuleCall_10_1_0 = (RuleCall)cNicknameAssignment_10_1.eContents().get(0);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cDeathCauseKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Assignment cDeathCauseAssignment_11_1 = (Assignment)cGroup_11.eContents().get(1);
		private final RuleCall cDeathCauseEStringParserRuleCall_11_1_0 = (RuleCall)cDeathCauseAssignment_11_1.eContents().get(0);
		private final Group cGroup_12 = (Group)cGroup.eContents().get(12);
		private final Keyword cMarriagesKeyword_12_0 = (Keyword)cGroup_12.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_12_1 = (Keyword)cGroup_12.eContents().get(1);
		private final Assignment cMarriagesAssignment_12_2 = (Assignment)cGroup_12.eContents().get(2);
		private final CrossReference cMarriagesMarriageCrossReference_12_2_0 = (CrossReference)cMarriagesAssignment_12_2.eContents().get(0);
		private final RuleCall cMarriagesMarriageEStringParserRuleCall_12_2_0_1 = (RuleCall)cMarriagesMarriageCrossReference_12_2_0.eContents().get(1);
		private final Group cGroup_12_3 = (Group)cGroup_12.eContents().get(3);
		private final Keyword cCommaKeyword_12_3_0 = (Keyword)cGroup_12_3.eContents().get(0);
		private final Assignment cMarriagesAssignment_12_3_1 = (Assignment)cGroup_12_3.eContents().get(1);
		private final CrossReference cMarriagesMarriageCrossReference_12_3_1_0 = (CrossReference)cMarriagesAssignment_12_3_1.eContents().get(0);
		private final RuleCall cMarriagesMarriageEStringParserRuleCall_12_3_1_0_1 = (RuleCall)cMarriagesMarriageCrossReference_12_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_12_4 = (Keyword)cGroup_12.eContents().get(4);
		private final Group cGroup_13 = (Group)cGroup.eContents().get(13);
		private final Keyword cCohabitationsKeyword_13_0 = (Keyword)cGroup_13.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_13_1 = (Keyword)cGroup_13.eContents().get(1);
		private final Assignment cCohabitationsAssignment_13_2 = (Assignment)cGroup_13.eContents().get(2);
		private final CrossReference cCohabitationsCohabitationCrossReference_13_2_0 = (CrossReference)cCohabitationsAssignment_13_2.eContents().get(0);
		private final RuleCall cCohabitationsCohabitationEStringParserRuleCall_13_2_0_1 = (RuleCall)cCohabitationsCohabitationCrossReference_13_2_0.eContents().get(1);
		private final Group cGroup_13_3 = (Group)cGroup_13.eContents().get(3);
		private final Keyword cCommaKeyword_13_3_0 = (Keyword)cGroup_13_3.eContents().get(0);
		private final Assignment cCohabitationsAssignment_13_3_1 = (Assignment)cGroup_13_3.eContents().get(1);
		private final CrossReference cCohabitationsCohabitationCrossReference_13_3_1_0 = (CrossReference)cCohabitationsAssignment_13_3_1.eContents().get(0);
		private final RuleCall cCohabitationsCohabitationEStringParserRuleCall_13_3_1_0_1 = (RuleCall)cCohabitationsCohabitationCrossReference_13_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_13_4 = (Keyword)cGroup_13.eContents().get(4);
		private final Group cGroup_14 = (Group)cGroup.eContents().get(14);
		private final Keyword cBirthDateKeyword_14_0 = (Keyword)cGroup_14.eContents().get(0);
		private final Assignment cBirthDateAssignment_14_1 = (Assignment)cGroup_14.eContents().get(1);
		private final RuleCall cBirthDateDateXParserRuleCall_14_1_0 = (RuleCall)cBirthDateAssignment_14_1.eContents().get(0);
		private final Group cGroup_15 = (Group)cGroup.eContents().get(15);
		private final Keyword cDeathDateKeyword_15_0 = (Keyword)cGroup_15.eContents().get(0);
		private final Assignment cDeathDateAssignment_15_1 = (Assignment)cGroup_15.eContents().get(1);
		private final RuleCall cDeathDateDateXParserRuleCall_15_1_0 = (RuleCall)cDeathDateAssignment_15_1.eContents().get(0);
		private final Group cGroup_16 = (Group)cGroup.eContents().get(16);
		private final Keyword cPersonhistoryKeyword_16_0 = (Keyword)cGroup_16.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_16_1 = (Keyword)cGroup_16.eContents().get(1);
		private final Assignment cPersonhistoryAssignment_16_2 = (Assignment)cGroup_16.eContents().get(2);
		private final RuleCall cPersonhistoryPersonHistoryParserRuleCall_16_2_0 = (RuleCall)cPersonhistoryAssignment_16_2.eContents().get(0);
		private final Group cGroup_16_3 = (Group)cGroup_16.eContents().get(3);
		private final Keyword cCommaKeyword_16_3_0 = (Keyword)cGroup_16_3.eContents().get(0);
		private final Assignment cPersonhistoryAssignment_16_3_1 = (Assignment)cGroup_16_3.eContents().get(1);
		private final RuleCall cPersonhistoryPersonHistoryParserRuleCall_16_3_1_0 = (RuleCall)cPersonhistoryAssignment_16_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_16_4 = (Keyword)cGroup_16.eContents().get(4);
		private final Group cGroup_17 = (Group)cGroup.eContents().get(17);
		private final Keyword cCohabitationKeyword_17_0 = (Keyword)cGroup_17.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_17_1 = (Keyword)cGroup_17.eContents().get(1);
		private final Assignment cCohabitationAssignment_17_2 = (Assignment)cGroup_17.eContents().get(2);
		private final RuleCall cCohabitationCohabitationParserRuleCall_17_2_0 = (RuleCall)cCohabitationAssignment_17_2.eContents().get(0);
		private final Group cGroup_17_3 = (Group)cGroup_17.eContents().get(3);
		private final Keyword cCommaKeyword_17_3_0 = (Keyword)cGroup_17_3.eContents().get(0);
		private final Assignment cCohabitationAssignment_17_3_1 = (Assignment)cGroup_17_3.eContents().get(1);
		private final RuleCall cCohabitationCohabitationParserRuleCall_17_3_1_0 = (RuleCall)cCohabitationAssignment_17_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_17_4 = (Keyword)cGroup_17.eContents().get(4);
		private final Group cGroup_18 = (Group)cGroup.eContents().get(18);
		private final Keyword cMarriageKeyword_18_0 = (Keyword)cGroup_18.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_18_1 = (Keyword)cGroup_18.eContents().get(1);
		private final Assignment cMarriageAssignment_18_2 = (Assignment)cGroup_18.eContents().get(2);
		private final RuleCall cMarriageMarriageParserRuleCall_18_2_0 = (RuleCall)cMarriageAssignment_18_2.eContents().get(0);
		private final Group cGroup_18_3 = (Group)cGroup_18.eContents().get(3);
		private final Keyword cCommaKeyword_18_3_0 = (Keyword)cGroup_18_3.eContents().get(0);
		private final Assignment cMarriageAssignment_18_3_1 = (Assignment)cGroup_18_3.eContents().get(1);
		private final RuleCall cMarriageMarriageParserRuleCall_18_3_1_0 = (RuleCall)cMarriageAssignment_18_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_18_4 = (Keyword)cGroup_18.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_19 = (Keyword)cGroup.eContents().get(19);
		
		//Person:
		//	'Person'
		//	'{' ('unknown' unknown=EBoolean) ('givenName' givenName=EString)? ('birthPlace' birthPlace=EString)? ('deathPlace'
		//	deathPlace=EString)? ('restingPlace' restingPlace=EString)? ('type' type=TypeOfPerson)? ('gender' gender=Gender)?
		//	('otherNames' '{' otherNames+=EString ("," otherNames+=EString)* '}')? ('nickname' nickname=EString)? ('deathCause'
		//	deathCause=EString)? ('marriages' '(' marriages+=[Marriage|EString] ("," marriages+=[Marriage|EString])* ')')?
		//	('cohabitations' '(' cohabitations+=[Cohabitation|EString] ("," cohabitations+=[Cohabitation|EString])* ')')?
		//	('birthDate' birthDate=DateX)? ('deathDate' deathDate=DateX)? ('personhistory' '{' personhistory+=PersonHistory (","
		//	personhistory+=PersonHistory)* '}')? ('cohabitation' '{' cohabitation+=Cohabitation ("," cohabitation+=Cohabitation)*
		//	'}')? ('marriage' '{' marriage+=Marriage ("," marriage+=Marriage)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Person' '{' ('unknown' unknown=EBoolean) ('givenName' givenName=EString)? ('birthPlace' birthPlace=EString)?
		//('deathPlace' deathPlace=EString)? ('restingPlace' restingPlace=EString)? ('type' type=TypeOfPerson)? ('gender'
		//gender=Gender)? ('otherNames' '{' otherNames+=EString ("," otherNames+=EString)* '}')? ('nickname' nickname=EString)?
		//('deathCause' deathCause=EString)? ('marriages' '(' marriages+=[Marriage|EString] ("," marriages+=[Marriage|EString])*
		//')')? ('cohabitations' '(' cohabitations+=[Cohabitation|EString] ("," cohabitations+=[Cohabitation|EString])* ')')?
		//('birthDate' birthDate=DateX)? ('deathDate' deathDate=DateX)? ('personhistory' '{' personhistory+=PersonHistory (","
		//personhistory+=PersonHistory)* '}')? ('cohabitation' '{' cohabitation+=Cohabitation ("," cohabitation+=Cohabitation)*
		//'}')? ('marriage' '{' marriage+=Marriage ("," marriage+=Marriage)* '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//'Person'
		public Keyword getPersonKeyword_0() { return cPersonKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//('unknown' unknown=EBoolean)
		public Group getGroup_2() { return cGroup_2; }
		
		//'unknown'
		public Keyword getUnknownKeyword_2_0() { return cUnknownKeyword_2_0; }
		
		//unknown=EBoolean
		public Assignment getUnknownAssignment_2_1() { return cUnknownAssignment_2_1; }
		
		//EBoolean
		public RuleCall getUnknownEBooleanParserRuleCall_2_1_0() { return cUnknownEBooleanParserRuleCall_2_1_0; }
		
		//('givenName' givenName=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'givenName'
		public Keyword getGivenNameKeyword_3_0() { return cGivenNameKeyword_3_0; }
		
		//givenName=EString
		public Assignment getGivenNameAssignment_3_1() { return cGivenNameAssignment_3_1; }
		
		//EString
		public RuleCall getGivenNameEStringParserRuleCall_3_1_0() { return cGivenNameEStringParserRuleCall_3_1_0; }
		
		//('birthPlace' birthPlace=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'birthPlace'
		public Keyword getBirthPlaceKeyword_4_0() { return cBirthPlaceKeyword_4_0; }
		
		//birthPlace=EString
		public Assignment getBirthPlaceAssignment_4_1() { return cBirthPlaceAssignment_4_1; }
		
		//EString
		public RuleCall getBirthPlaceEStringParserRuleCall_4_1_0() { return cBirthPlaceEStringParserRuleCall_4_1_0; }
		
		//('deathPlace' deathPlace=EString)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'deathPlace'
		public Keyword getDeathPlaceKeyword_5_0() { return cDeathPlaceKeyword_5_0; }
		
		//deathPlace=EString
		public Assignment getDeathPlaceAssignment_5_1() { return cDeathPlaceAssignment_5_1; }
		
		//EString
		public RuleCall getDeathPlaceEStringParserRuleCall_5_1_0() { return cDeathPlaceEStringParserRuleCall_5_1_0; }
		
		//('restingPlace' restingPlace=EString)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'restingPlace'
		public Keyword getRestingPlaceKeyword_6_0() { return cRestingPlaceKeyword_6_0; }
		
		//restingPlace=EString
		public Assignment getRestingPlaceAssignment_6_1() { return cRestingPlaceAssignment_6_1; }
		
		//EString
		public RuleCall getRestingPlaceEStringParserRuleCall_6_1_0() { return cRestingPlaceEStringParserRuleCall_6_1_0; }
		
		//('type' type=TypeOfPerson)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'type'
		public Keyword getTypeKeyword_7_0() { return cTypeKeyword_7_0; }
		
		//type=TypeOfPerson
		public Assignment getTypeAssignment_7_1() { return cTypeAssignment_7_1; }
		
		//TypeOfPerson
		public RuleCall getTypeTypeOfPersonEnumRuleCall_7_1_0() { return cTypeTypeOfPersonEnumRuleCall_7_1_0; }
		
		//('gender' gender=Gender)?
		public Group getGroup_8() { return cGroup_8; }
		
		//'gender'
		public Keyword getGenderKeyword_8_0() { return cGenderKeyword_8_0; }
		
		//gender=Gender
		public Assignment getGenderAssignment_8_1() { return cGenderAssignment_8_1; }
		
		//Gender
		public RuleCall getGenderGenderEnumRuleCall_8_1_0() { return cGenderGenderEnumRuleCall_8_1_0; }
		
		//('otherNames' '{' otherNames+=EString ("," otherNames+=EString)* '}')?
		public Group getGroup_9() { return cGroup_9; }
		
		//'otherNames'
		public Keyword getOtherNamesKeyword_9_0() { return cOtherNamesKeyword_9_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_9_1() { return cLeftCurlyBracketKeyword_9_1; }
		
		//otherNames+=EString
		public Assignment getOtherNamesAssignment_9_2() { return cOtherNamesAssignment_9_2; }
		
		//EString
		public RuleCall getOtherNamesEStringParserRuleCall_9_2_0() { return cOtherNamesEStringParserRuleCall_9_2_0; }
		
		//("," otherNames+=EString)*
		public Group getGroup_9_3() { return cGroup_9_3; }
		
		//","
		public Keyword getCommaKeyword_9_3_0() { return cCommaKeyword_9_3_0; }
		
		//otherNames+=EString
		public Assignment getOtherNamesAssignment_9_3_1() { return cOtherNamesAssignment_9_3_1; }
		
		//EString
		public RuleCall getOtherNamesEStringParserRuleCall_9_3_1_0() { return cOtherNamesEStringParserRuleCall_9_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9_4() { return cRightCurlyBracketKeyword_9_4; }
		
		//('nickname' nickname=EString)?
		public Group getGroup_10() { return cGroup_10; }
		
		//'nickname'
		public Keyword getNicknameKeyword_10_0() { return cNicknameKeyword_10_0; }
		
		//nickname=EString
		public Assignment getNicknameAssignment_10_1() { return cNicknameAssignment_10_1; }
		
		//EString
		public RuleCall getNicknameEStringParserRuleCall_10_1_0() { return cNicknameEStringParserRuleCall_10_1_0; }
		
		//('deathCause' deathCause=EString)?
		public Group getGroup_11() { return cGroup_11; }
		
		//'deathCause'
		public Keyword getDeathCauseKeyword_11_0() { return cDeathCauseKeyword_11_0; }
		
		//deathCause=EString
		public Assignment getDeathCauseAssignment_11_1() { return cDeathCauseAssignment_11_1; }
		
		//EString
		public RuleCall getDeathCauseEStringParserRuleCall_11_1_0() { return cDeathCauseEStringParserRuleCall_11_1_0; }
		
		//('marriages' '(' marriages+=[Marriage|EString] ("," marriages+=[Marriage|EString])* ')')?
		public Group getGroup_12() { return cGroup_12; }
		
		//'marriages'
		public Keyword getMarriagesKeyword_12_0() { return cMarriagesKeyword_12_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_12_1() { return cLeftParenthesisKeyword_12_1; }
		
		//marriages+=[Marriage|EString]
		public Assignment getMarriagesAssignment_12_2() { return cMarriagesAssignment_12_2; }
		
		//[Marriage|EString]
		public CrossReference getMarriagesMarriageCrossReference_12_2_0() { return cMarriagesMarriageCrossReference_12_2_0; }
		
		//EString
		public RuleCall getMarriagesMarriageEStringParserRuleCall_12_2_0_1() { return cMarriagesMarriageEStringParserRuleCall_12_2_0_1; }
		
		//("," marriages+=[Marriage|EString])*
		public Group getGroup_12_3() { return cGroup_12_3; }
		
		//","
		public Keyword getCommaKeyword_12_3_0() { return cCommaKeyword_12_3_0; }
		
		//marriages+=[Marriage|EString]
		public Assignment getMarriagesAssignment_12_3_1() { return cMarriagesAssignment_12_3_1; }
		
		//[Marriage|EString]
		public CrossReference getMarriagesMarriageCrossReference_12_3_1_0() { return cMarriagesMarriageCrossReference_12_3_1_0; }
		
		//EString
		public RuleCall getMarriagesMarriageEStringParserRuleCall_12_3_1_0_1() { return cMarriagesMarriageEStringParserRuleCall_12_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_12_4() { return cRightParenthesisKeyword_12_4; }
		
		//('cohabitations' '(' cohabitations+=[Cohabitation|EString] ("," cohabitations+=[Cohabitation|EString])* ')')?
		public Group getGroup_13() { return cGroup_13; }
		
		//'cohabitations'
		public Keyword getCohabitationsKeyword_13_0() { return cCohabitationsKeyword_13_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_13_1() { return cLeftParenthesisKeyword_13_1; }
		
		//cohabitations+=[Cohabitation|EString]
		public Assignment getCohabitationsAssignment_13_2() { return cCohabitationsAssignment_13_2; }
		
		//[Cohabitation|EString]
		public CrossReference getCohabitationsCohabitationCrossReference_13_2_0() { return cCohabitationsCohabitationCrossReference_13_2_0; }
		
		//EString
		public RuleCall getCohabitationsCohabitationEStringParserRuleCall_13_2_0_1() { return cCohabitationsCohabitationEStringParserRuleCall_13_2_0_1; }
		
		//("," cohabitations+=[Cohabitation|EString])*
		public Group getGroup_13_3() { return cGroup_13_3; }
		
		//","
		public Keyword getCommaKeyword_13_3_0() { return cCommaKeyword_13_3_0; }
		
		//cohabitations+=[Cohabitation|EString]
		public Assignment getCohabitationsAssignment_13_3_1() { return cCohabitationsAssignment_13_3_1; }
		
		//[Cohabitation|EString]
		public CrossReference getCohabitationsCohabitationCrossReference_13_3_1_0() { return cCohabitationsCohabitationCrossReference_13_3_1_0; }
		
		//EString
		public RuleCall getCohabitationsCohabitationEStringParserRuleCall_13_3_1_0_1() { return cCohabitationsCohabitationEStringParserRuleCall_13_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_13_4() { return cRightParenthesisKeyword_13_4; }
		
		//('birthDate' birthDate=DateX)?
		public Group getGroup_14() { return cGroup_14; }
		
		//'birthDate'
		public Keyword getBirthDateKeyword_14_0() { return cBirthDateKeyword_14_0; }
		
		//birthDate=DateX
		public Assignment getBirthDateAssignment_14_1() { return cBirthDateAssignment_14_1; }
		
		//DateX
		public RuleCall getBirthDateDateXParserRuleCall_14_1_0() { return cBirthDateDateXParserRuleCall_14_1_0; }
		
		//('deathDate' deathDate=DateX)?
		public Group getGroup_15() { return cGroup_15; }
		
		//'deathDate'
		public Keyword getDeathDateKeyword_15_0() { return cDeathDateKeyword_15_0; }
		
		//deathDate=DateX
		public Assignment getDeathDateAssignment_15_1() { return cDeathDateAssignment_15_1; }
		
		//DateX
		public RuleCall getDeathDateDateXParserRuleCall_15_1_0() { return cDeathDateDateXParserRuleCall_15_1_0; }
		
		//('personhistory' '{' personhistory+=PersonHistory ("," personhistory+=PersonHistory)* '}')?
		public Group getGroup_16() { return cGroup_16; }
		
		//'personhistory'
		public Keyword getPersonhistoryKeyword_16_0() { return cPersonhistoryKeyword_16_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_16_1() { return cLeftCurlyBracketKeyword_16_1; }
		
		//personhistory+=PersonHistory
		public Assignment getPersonhistoryAssignment_16_2() { return cPersonhistoryAssignment_16_2; }
		
		//PersonHistory
		public RuleCall getPersonhistoryPersonHistoryParserRuleCall_16_2_0() { return cPersonhistoryPersonHistoryParserRuleCall_16_2_0; }
		
		//("," personhistory+=PersonHistory)*
		public Group getGroup_16_3() { return cGroup_16_3; }
		
		//","
		public Keyword getCommaKeyword_16_3_0() { return cCommaKeyword_16_3_0; }
		
		//personhistory+=PersonHistory
		public Assignment getPersonhistoryAssignment_16_3_1() { return cPersonhistoryAssignment_16_3_1; }
		
		//PersonHistory
		public RuleCall getPersonhistoryPersonHistoryParserRuleCall_16_3_1_0() { return cPersonhistoryPersonHistoryParserRuleCall_16_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_16_4() { return cRightCurlyBracketKeyword_16_4; }
		
		//('cohabitation' '{' cohabitation+=Cohabitation ("," cohabitation+=Cohabitation)* '}')?
		public Group getGroup_17() { return cGroup_17; }
		
		//'cohabitation'
		public Keyword getCohabitationKeyword_17_0() { return cCohabitationKeyword_17_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_17_1() { return cLeftCurlyBracketKeyword_17_1; }
		
		//cohabitation+=Cohabitation
		public Assignment getCohabitationAssignment_17_2() { return cCohabitationAssignment_17_2; }
		
		//Cohabitation
		public RuleCall getCohabitationCohabitationParserRuleCall_17_2_0() { return cCohabitationCohabitationParserRuleCall_17_2_0; }
		
		//("," cohabitation+=Cohabitation)*
		public Group getGroup_17_3() { return cGroup_17_3; }
		
		//","
		public Keyword getCommaKeyword_17_3_0() { return cCommaKeyword_17_3_0; }
		
		//cohabitation+=Cohabitation
		public Assignment getCohabitationAssignment_17_3_1() { return cCohabitationAssignment_17_3_1; }
		
		//Cohabitation
		public RuleCall getCohabitationCohabitationParserRuleCall_17_3_1_0() { return cCohabitationCohabitationParserRuleCall_17_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_17_4() { return cRightCurlyBracketKeyword_17_4; }
		
		//('marriage' '{' marriage+=Marriage ("," marriage+=Marriage)* '}')?
		public Group getGroup_18() { return cGroup_18; }
		
		//'marriage'
		public Keyword getMarriageKeyword_18_0() { return cMarriageKeyword_18_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_18_1() { return cLeftCurlyBracketKeyword_18_1; }
		
		//marriage+=Marriage
		public Assignment getMarriageAssignment_18_2() { return cMarriageAssignment_18_2; }
		
		//Marriage
		public RuleCall getMarriageMarriageParserRuleCall_18_2_0() { return cMarriageMarriageParserRuleCall_18_2_0; }
		
		//("," marriage+=Marriage)*
		public Group getGroup_18_3() { return cGroup_18_3; }
		
		//","
		public Keyword getCommaKeyword_18_3_0() { return cCommaKeyword_18_3_0; }
		
		//marriage+=Marriage
		public Assignment getMarriageAssignment_18_3_1() { return cMarriageAssignment_18_3_1; }
		
		//Marriage
		public RuleCall getMarriageMarriageParserRuleCall_18_3_1_0() { return cMarriageMarriageParserRuleCall_18_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_18_4() { return cRightCurlyBracketKeyword_18_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_19() { return cRightCurlyBracketKeyword_19; }
	}
	public class EIntegerObjectElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.gendsl.GenDsl.EIntegerObject");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EIntegerObject ecore::EIntegerObject:
		//	'-'? INT
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	public class MarriageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.gendsl.GenDsl.Marriage");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cMarriageAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cMarriageKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cTypeKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cTypeAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cTypeTypeOfIntimateRelationshipEnumRuleCall_3_1_0 = (RuleCall)cTypeAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cSpousesKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cSpousesAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final CrossReference cSpousesPersonCrossReference_4_2_0 = (CrossReference)cSpousesAssignment_4_2.eContents().get(0);
		private final RuleCall cSpousesPersonEStringParserRuleCall_4_2_0_1 = (RuleCall)cSpousesPersonCrossReference_4_2_0.eContents().get(1);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cSpousesAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final CrossReference cSpousesPersonCrossReference_4_3_1_0 = (CrossReference)cSpousesAssignment_4_3_1.eContents().get(0);
		private final RuleCall cSpousesPersonEStringParserRuleCall_4_3_1_0_1 = (RuleCall)cSpousesPersonCrossReference_4_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cFromDateKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cFromDateAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cFromDateDateXParserRuleCall_5_1_0 = (RuleCall)cFromDateAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cToDateKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cToDateAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cToDateDateXParserRuleCall_6_1_0 = (RuleCall)cToDateAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cChildrenKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cChildrenAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cChildrenPersonParserRuleCall_7_2_0 = (RuleCall)cChildrenAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cChildrenAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cChildrenPersonParserRuleCall_7_3_1_0 = (RuleCall)cChildrenAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Marriage:
		//	{Marriage}
		//	'Marriage'
		//	'{' ('type' type=TypeOfIntimateRelationship)? ('spouses' '(' spouses+=[Person|EString] (","
		//	spouses+=[Person|EString])* ')')? ('fromDate' fromDate=DateX)? ('toDate' toDate=DateX)? ('children' '{'
		//	children+=Person ("," children+=Person)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Marriage} 'Marriage' '{' ('type' type=TypeOfIntimateRelationship)? ('spouses' '(' spouses+=[Person|EString] (","
		//spouses+=[Person|EString])* ')')? ('fromDate' fromDate=DateX)? ('toDate' toDate=DateX)? ('children' '{'
		//children+=Person ("," children+=Person)* '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//{Marriage}
		public Action getMarriageAction_0() { return cMarriageAction_0; }
		
		//'Marriage'
		public Keyword getMarriageKeyword_1() { return cMarriageKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('type' type=TypeOfIntimateRelationship)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'type'
		public Keyword getTypeKeyword_3_0() { return cTypeKeyword_3_0; }
		
		//type=TypeOfIntimateRelationship
		public Assignment getTypeAssignment_3_1() { return cTypeAssignment_3_1; }
		
		//TypeOfIntimateRelationship
		public RuleCall getTypeTypeOfIntimateRelationshipEnumRuleCall_3_1_0() { return cTypeTypeOfIntimateRelationshipEnumRuleCall_3_1_0; }
		
		//('spouses' '(' spouses+=[Person|EString] ("," spouses+=[Person|EString])* ')')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'spouses'
		public Keyword getSpousesKeyword_4_0() { return cSpousesKeyword_4_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4_1() { return cLeftParenthesisKeyword_4_1; }
		
		//spouses+=[Person|EString]
		public Assignment getSpousesAssignment_4_2() { return cSpousesAssignment_4_2; }
		
		//[Person|EString]
		public CrossReference getSpousesPersonCrossReference_4_2_0() { return cSpousesPersonCrossReference_4_2_0; }
		
		//EString
		public RuleCall getSpousesPersonEStringParserRuleCall_4_2_0_1() { return cSpousesPersonEStringParserRuleCall_4_2_0_1; }
		
		//("," spouses+=[Person|EString])*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//spouses+=[Person|EString]
		public Assignment getSpousesAssignment_4_3_1() { return cSpousesAssignment_4_3_1; }
		
		//[Person|EString]
		public CrossReference getSpousesPersonCrossReference_4_3_1_0() { return cSpousesPersonCrossReference_4_3_1_0; }
		
		//EString
		public RuleCall getSpousesPersonEStringParserRuleCall_4_3_1_0_1() { return cSpousesPersonEStringParserRuleCall_4_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4_4() { return cRightParenthesisKeyword_4_4; }
		
		//('fromDate' fromDate=DateX)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'fromDate'
		public Keyword getFromDateKeyword_5_0() { return cFromDateKeyword_5_0; }
		
		//fromDate=DateX
		public Assignment getFromDateAssignment_5_1() { return cFromDateAssignment_5_1; }
		
		//DateX
		public RuleCall getFromDateDateXParserRuleCall_5_1_0() { return cFromDateDateXParserRuleCall_5_1_0; }
		
		//('toDate' toDate=DateX)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'toDate'
		public Keyword getToDateKeyword_6_0() { return cToDateKeyword_6_0; }
		
		//toDate=DateX
		public Assignment getToDateAssignment_6_1() { return cToDateAssignment_6_1; }
		
		//DateX
		public RuleCall getToDateDateXParserRuleCall_6_1_0() { return cToDateDateXParserRuleCall_6_1_0; }
		
		//('children' '{' children+=Person ("," children+=Person)* '}')?
		public Group getGroup_7() { return cGroup_7; }
		
		//'children'
		public Keyword getChildrenKeyword_7_0() { return cChildrenKeyword_7_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }
		
		//children+=Person
		public Assignment getChildrenAssignment_7_2() { return cChildrenAssignment_7_2; }
		
		//Person
		public RuleCall getChildrenPersonParserRuleCall_7_2_0() { return cChildrenPersonParserRuleCall_7_2_0; }
		
		//("," children+=Person)*
		public Group getGroup_7_3() { return cGroup_7_3; }
		
		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }
		
		//children+=Person
		public Assignment getChildrenAssignment_7_3_1() { return cChildrenAssignment_7_3_1; }
		
		//Person
		public RuleCall getChildrenPersonParserRuleCall_7_3_1_0() { return cChildrenPersonParserRuleCall_7_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class CohabitationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.gendsl.GenDsl.Cohabitation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cCohabitationAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cLegitimateAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cLegitimateLegitimateKeyword_1_0 = (Keyword)cLegitimateAssignment_1.eContents().get(0);
		private final Keyword cCohabitationKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cTypeKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cTypeAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cTypeTypeOfIntimateRelationshipEnumRuleCall_4_1_0 = (RuleCall)cTypeAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cPartnersKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cPartnersAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final CrossReference cPartnersPersonCrossReference_5_2_0 = (CrossReference)cPartnersAssignment_5_2.eContents().get(0);
		private final RuleCall cPartnersPersonEStringParserRuleCall_5_2_0_1 = (RuleCall)cPartnersPersonCrossReference_5_2_0.eContents().get(1);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cPartnersAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final CrossReference cPartnersPersonCrossReference_5_3_1_0 = (CrossReference)cPartnersAssignment_5_3_1.eContents().get(0);
		private final RuleCall cPartnersPersonEStringParserRuleCall_5_3_1_0_1 = (RuleCall)cPartnersPersonCrossReference_5_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cChildrenKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cChildrenAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cChildrenPersonParserRuleCall_6_2_0 = (RuleCall)cChildrenAssignment_6_2.eContents().get(0);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cChildrenAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final RuleCall cChildrenPersonParserRuleCall_6_3_1_0 = (RuleCall)cChildrenAssignment_6_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Cohabitation:
		//	{Cohabitation} legitimate?='legitimate'?
		//	'Cohabitation'
		//	'{' ('type' type=TypeOfIntimateRelationship)? ('partners' '(' partners+=[Person|EString] (","
		//	partners+=[Person|EString])* ')')? ('children' '{' children+=Person ("," children+=Person)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Cohabitation} legitimate?='legitimate'? 'Cohabitation' '{' ('type' type=TypeOfIntimateRelationship)? ('partners' '('
		//partners+=[Person|EString] ("," partners+=[Person|EString])* ')')? ('children' '{' children+=Person (","
		//children+=Person)* '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//{Cohabitation}
		public Action getCohabitationAction_0() { return cCohabitationAction_0; }
		
		//legitimate?='legitimate'?
		public Assignment getLegitimateAssignment_1() { return cLegitimateAssignment_1; }
		
		//'legitimate'
		public Keyword getLegitimateLegitimateKeyword_1_0() { return cLegitimateLegitimateKeyword_1_0; }
		
		//'Cohabitation'
		public Keyword getCohabitationKeyword_2() { return cCohabitationKeyword_2; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('type' type=TypeOfIntimateRelationship)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'type'
		public Keyword getTypeKeyword_4_0() { return cTypeKeyword_4_0; }
		
		//type=TypeOfIntimateRelationship
		public Assignment getTypeAssignment_4_1() { return cTypeAssignment_4_1; }
		
		//TypeOfIntimateRelationship
		public RuleCall getTypeTypeOfIntimateRelationshipEnumRuleCall_4_1_0() { return cTypeTypeOfIntimateRelationshipEnumRuleCall_4_1_0; }
		
		//('partners' '(' partners+=[Person|EString] ("," partners+=[Person|EString])* ')')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'partners'
		public Keyword getPartnersKeyword_5_0() { return cPartnersKeyword_5_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_5_1() { return cLeftParenthesisKeyword_5_1; }
		
		//partners+=[Person|EString]
		public Assignment getPartnersAssignment_5_2() { return cPartnersAssignment_5_2; }
		
		//[Person|EString]
		public CrossReference getPartnersPersonCrossReference_5_2_0() { return cPartnersPersonCrossReference_5_2_0; }
		
		//EString
		public RuleCall getPartnersPersonEStringParserRuleCall_5_2_0_1() { return cPartnersPersonEStringParserRuleCall_5_2_0_1; }
		
		//("," partners+=[Person|EString])*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//partners+=[Person|EString]
		public Assignment getPartnersAssignment_5_3_1() { return cPartnersAssignment_5_3_1; }
		
		//[Person|EString]
		public CrossReference getPartnersPersonCrossReference_5_3_1_0() { return cPartnersPersonCrossReference_5_3_1_0; }
		
		//EString
		public RuleCall getPartnersPersonEStringParserRuleCall_5_3_1_0_1() { return cPartnersPersonEStringParserRuleCall_5_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5_4() { return cRightParenthesisKeyword_5_4; }
		
		//('children' '{' children+=Person ("," children+=Person)* '}')?
		public Group getGroup_6() { return cGroup_6; }
		
		//'children'
		public Keyword getChildrenKeyword_6_0() { return cChildrenKeyword_6_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6_1() { return cLeftCurlyBracketKeyword_6_1; }
		
		//children+=Person
		public Assignment getChildrenAssignment_6_2() { return cChildrenAssignment_6_2; }
		
		//Person
		public RuleCall getChildrenPersonParserRuleCall_6_2_0() { return cChildrenPersonParserRuleCall_6_2_0; }
		
		//("," children+=Person)*
		public Group getGroup_6_3() { return cGroup_6_3; }
		
		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }
		
		//children+=Person
		public Assignment getChildrenAssignment_6_3_1() { return cChildrenAssignment_6_3_1; }
		
		//Person
		public RuleCall getChildrenPersonParserRuleCall_6_3_1_0() { return cChildrenPersonParserRuleCall_6_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6_4() { return cRightCurlyBracketKeyword_6_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class PersonHistoryElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.gendsl.GenDsl.PersonHistory");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cPersonHistoryAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cPersonHistoryKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cGenderKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cGenderAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cGenderGenderEnumRuleCall_3_1_0 = (RuleCall)cGenderAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cGivenNameKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cGivenNameAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cGivenNameEStringParserRuleCall_4_1_0 = (RuleCall)cGivenNameAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cChangedKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cChangedAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cChangedEDateParserRuleCall_5_1_0 = (RuleCall)cChangedAssignment_5_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//PersonHistory:
		//	{PersonHistory}
		//	'PersonHistory'
		//	'{' ('gender' gender=Gender)? ('givenName' givenName=EString)? ('changed' changed=EDate)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{PersonHistory} 'PersonHistory' '{' ('gender' gender=Gender)? ('givenName' givenName=EString)? ('changed'
		//changed=EDate)? '}'
		public Group getGroup() { return cGroup; }
		
		//{PersonHistory}
		public Action getPersonHistoryAction_0() { return cPersonHistoryAction_0; }
		
		//'PersonHistory'
		public Keyword getPersonHistoryKeyword_1() { return cPersonHistoryKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('gender' gender=Gender)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'gender'
		public Keyword getGenderKeyword_3_0() { return cGenderKeyword_3_0; }
		
		//gender=Gender
		public Assignment getGenderAssignment_3_1() { return cGenderAssignment_3_1; }
		
		//Gender
		public RuleCall getGenderGenderEnumRuleCall_3_1_0() { return cGenderGenderEnumRuleCall_3_1_0; }
		
		//('givenName' givenName=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'givenName'
		public Keyword getGivenNameKeyword_4_0() { return cGivenNameKeyword_4_0; }
		
		//givenName=EString
		public Assignment getGivenNameAssignment_4_1() { return cGivenNameAssignment_4_1; }
		
		//EString
		public RuleCall getGivenNameEStringParserRuleCall_4_1_0() { return cGivenNameEStringParserRuleCall_4_1_0; }
		
		//('changed' changed=EDate)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'changed'
		public Keyword getChangedKeyword_5_0() { return cChangedKeyword_5_0; }
		
		//changed=EDate
		public Assignment getChangedAssignment_5_1() { return cChangedAssignment_5_1; }
		
		//EDate
		public RuleCall getChangedEDateParserRuleCall_5_1_0() { return cChangedEDateParserRuleCall_5_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.gendsl.GenDsl.EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean ecore::EBoolean:
		//	'true' | 'false'
		@Override public ParserRule getRule() { return rule; }
		
		//'true' | 'false'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'true'
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }
		
		//'false'
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}
	public class EDateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.gendsl.GenDsl.EDate");
		private final Keyword cEDateKeyword = (Keyword)rule.eContents().get(1);
		
		//EDate ecore::EDate:
		//	'EDate'
		@Override public ParserRule getRule() { return rule; }
		
		//'EDate'
		public Keyword getEDateKeyword() { return cEDateKeyword; }
	}
	
	public class TypeOfPersonElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.gendsl.GenDsl.TypeOfPerson");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cBIOLOGICALEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cBIOLOGICALBIOLOGICALKeyword_0_0 = (Keyword)cBIOLOGICALEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cADOPTEDEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cADOPTEDADOPTEDKeyword_1_0 = (Keyword)cADOPTEDEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cSEMIADOPTEDEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cSEMIADOPTEDSEMIADOPTEDKeyword_2_0 = (Keyword)cSEMIADOPTEDEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cMARRIEDEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cMARRIEDMARRIEDKeyword_3_0 = (Keyword)cMARRIEDEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cDISOWNEDEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cDISOWNEDDISOWNEDKeyword_4_0 = (Keyword)cDISOWNEDEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cILLEGITIMATEEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cILLEGITIMATEILLEGITIMATEKeyword_5_0 = (Keyword)cILLEGITIMATEEnumLiteralDeclaration_5.eContents().get(0);
		
		//enum TypeOfPerson:
		//	BIOLOGICAL | ADOPTED | SEMIADOPTED | MARRIED | DISOWNED | ILLEGITIMATE;
		public EnumRule getRule() { return rule; }
		
		//BIOLOGICAL | ADOPTED | SEMIADOPTED | MARRIED | DISOWNED | ILLEGITIMATE
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//BIOLOGICAL
		public EnumLiteralDeclaration getBIOLOGICALEnumLiteralDeclaration_0() { return cBIOLOGICALEnumLiteralDeclaration_0; }
		
		//'BIOLOGICAL'
		public Keyword getBIOLOGICALBIOLOGICALKeyword_0_0() { return cBIOLOGICALBIOLOGICALKeyword_0_0; }
		
		//ADOPTED
		public EnumLiteralDeclaration getADOPTEDEnumLiteralDeclaration_1() { return cADOPTEDEnumLiteralDeclaration_1; }
		
		//'ADOPTED'
		public Keyword getADOPTEDADOPTEDKeyword_1_0() { return cADOPTEDADOPTEDKeyword_1_0; }
		
		//SEMIADOPTED
		public EnumLiteralDeclaration getSEMIADOPTEDEnumLiteralDeclaration_2() { return cSEMIADOPTEDEnumLiteralDeclaration_2; }
		
		//'SEMIADOPTED'
		public Keyword getSEMIADOPTEDSEMIADOPTEDKeyword_2_0() { return cSEMIADOPTEDSEMIADOPTEDKeyword_2_0; }
		
		//MARRIED
		public EnumLiteralDeclaration getMARRIEDEnumLiteralDeclaration_3() { return cMARRIEDEnumLiteralDeclaration_3; }
		
		//'MARRIED'
		public Keyword getMARRIEDMARRIEDKeyword_3_0() { return cMARRIEDMARRIEDKeyword_3_0; }
		
		//DISOWNED
		public EnumLiteralDeclaration getDISOWNEDEnumLiteralDeclaration_4() { return cDISOWNEDEnumLiteralDeclaration_4; }
		
		//'DISOWNED'
		public Keyword getDISOWNEDDISOWNEDKeyword_4_0() { return cDISOWNEDDISOWNEDKeyword_4_0; }
		
		//ILLEGITIMATE
		public EnumLiteralDeclaration getILLEGITIMATEEnumLiteralDeclaration_5() { return cILLEGITIMATEEnumLiteralDeclaration_5; }
		
		//'ILLEGITIMATE'
		public Keyword getILLEGITIMATEILLEGITIMATEKeyword_5_0() { return cILLEGITIMATEILLEGITIMATEKeyword_5_0; }
	}
	public class GenderElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.gendsl.GenDsl.Gender");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cMALEEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cMALEMALEKeyword_0_0 = (Keyword)cMALEEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cFEMALEEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cFEMALEFEMALEKeyword_1_0 = (Keyword)cFEMALEEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cBIGENDEREnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cBIGENDERBIGENDERKeyword_2_0 = (Keyword)cBIGENDEREnumLiteralDeclaration_2.eContents().get(0);
		
		//enum Gender:
		//	MALE | FEMALE | BIGENDER;
		public EnumRule getRule() { return rule; }
		
		//MALE | FEMALE | BIGENDER
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//MALE
		public EnumLiteralDeclaration getMALEEnumLiteralDeclaration_0() { return cMALEEnumLiteralDeclaration_0; }
		
		//'MALE'
		public Keyword getMALEMALEKeyword_0_0() { return cMALEMALEKeyword_0_0; }
		
		//FEMALE
		public EnumLiteralDeclaration getFEMALEEnumLiteralDeclaration_1() { return cFEMALEEnumLiteralDeclaration_1; }
		
		//'FEMALE'
		public Keyword getFEMALEFEMALEKeyword_1_0() { return cFEMALEFEMALEKeyword_1_0; }
		
		//BIGENDER
		public EnumLiteralDeclaration getBIGENDEREnumLiteralDeclaration_2() { return cBIGENDEREnumLiteralDeclaration_2; }
		
		//'BIGENDER'
		public Keyword getBIGENDERBIGENDERKeyword_2_0() { return cBIGENDERBIGENDERKeyword_2_0; }
	}
	public class TypeOfIntimateRelationshipElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.gendsl.GenDsl.TypeOfIntimateRelationship");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cMONOGAMYEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cMONOGAMYMONOGAMYKeyword_0_0 = (Keyword)cMONOGAMYEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cPOLYGAMYEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cPOLYGAMYPOLYGAMYKeyword_1_0 = (Keyword)cPOLYGAMYEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cPOLYFIDELITYEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cPOLYFIDELITYPOLYFIDELITYKeyword_2_0 = (Keyword)cPOLYFIDELITYEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum TypeOfIntimateRelationship:
		//	MONOGAMY | POLYGAMY | POLYFIDELITY;
		public EnumRule getRule() { return rule; }
		
		//MONOGAMY | POLYGAMY | POLYFIDELITY
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//MONOGAMY
		public EnumLiteralDeclaration getMONOGAMYEnumLiteralDeclaration_0() { return cMONOGAMYEnumLiteralDeclaration_0; }
		
		//'MONOGAMY'
		public Keyword getMONOGAMYMONOGAMYKeyword_0_0() { return cMONOGAMYMONOGAMYKeyword_0_0; }
		
		//POLYGAMY
		public EnumLiteralDeclaration getPOLYGAMYEnumLiteralDeclaration_1() { return cPOLYGAMYEnumLiteralDeclaration_1; }
		
		//'POLYGAMY'
		public Keyword getPOLYGAMYPOLYGAMYKeyword_1_0() { return cPOLYGAMYPOLYGAMYKeyword_1_0; }
		
		//POLYFIDELITY
		public EnumLiteralDeclaration getPOLYFIDELITYEnumLiteralDeclaration_2() { return cPOLYFIDELITYEnumLiteralDeclaration_2; }
		
		//'POLYFIDELITY'
		public Keyword getPOLYFIDELITYPOLYFIDELITYKeyword_2_0() { return cPOLYFIDELITYPOLYFIDELITYKeyword_2_0; }
	}
	
	private final GenealogyTreeElements pGenealogyTree;
	private final EStringElements pEString;
	private final DateXElements pDateX;
	private final PersonElements pPerson;
	private final EIntegerObjectElements pEIntegerObject;
	private final TypeOfPersonElements eTypeOfPerson;
	private final GenderElements eGender;
	private final MarriageElements pMarriage;
	private final CohabitationElements pCohabitation;
	private final PersonHistoryElements pPersonHistory;
	private final EBooleanElements pEBoolean;
	private final TypeOfIntimateRelationshipElements eTypeOfIntimateRelationship;
	private final EDateElements pEDate;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public GenDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pGenealogyTree = new GenealogyTreeElements();
		this.pEString = new EStringElements();
		this.pDateX = new DateXElements();
		this.pPerson = new PersonElements();
		this.pEIntegerObject = new EIntegerObjectElements();
		this.eTypeOfPerson = new TypeOfPersonElements();
		this.eGender = new GenderElements();
		this.pMarriage = new MarriageElements();
		this.pCohabitation = new CohabitationElements();
		this.pPersonHistory = new PersonHistoryElements();
		this.pEBoolean = new EBooleanElements();
		this.eTypeOfIntimateRelationship = new TypeOfIntimateRelationshipElements();
		this.pEDate = new EDateElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.gendsl.GenDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//GenealogyTree:
	//	'GenealogyTree'
	//	'{'
	//	'familyName' familyName=EString ('established' established=DateX)? ('person' '{' person+=Person ("," person+=Person)*
	//	'}')?
	//	'}';
	public GenealogyTreeElements getGenealogyTreeAccess() {
		return pGenealogyTree;
	}
	
	public ParserRule getGenealogyTreeRule() {
		return getGenealogyTreeAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//DateX:
	//	{DateX}
	//	'DateX'
	//	'{' ('year' year=EIntegerObject)? ('month' month=EIntegerObject)? ('day' day=EIntegerObject)?
	//	'}';
	public DateXElements getDateXAccess() {
		return pDateX;
	}
	
	public ParserRule getDateXRule() {
		return getDateXAccess().getRule();
	}
	
	//Person:
	//	'Person'
	//	'{' ('unknown' unknown=EBoolean) ('givenName' givenName=EString)? ('birthPlace' birthPlace=EString)? ('deathPlace'
	//	deathPlace=EString)? ('restingPlace' restingPlace=EString)? ('type' type=TypeOfPerson)? ('gender' gender=Gender)?
	//	('otherNames' '{' otherNames+=EString ("," otherNames+=EString)* '}')? ('nickname' nickname=EString)? ('deathCause'
	//	deathCause=EString)? ('marriages' '(' marriages+=[Marriage|EString] ("," marriages+=[Marriage|EString])* ')')?
	//	('cohabitations' '(' cohabitations+=[Cohabitation|EString] ("," cohabitations+=[Cohabitation|EString])* ')')?
	//	('birthDate' birthDate=DateX)? ('deathDate' deathDate=DateX)? ('personhistory' '{' personhistory+=PersonHistory (","
	//	personhistory+=PersonHistory)* '}')? ('cohabitation' '{' cohabitation+=Cohabitation ("," cohabitation+=Cohabitation)*
	//	'}')? ('marriage' '{' marriage+=Marriage ("," marriage+=Marriage)* '}')?
	//	'}';
	public PersonElements getPersonAccess() {
		return pPerson;
	}
	
	public ParserRule getPersonRule() {
		return getPersonAccess().getRule();
	}
	
	//EIntegerObject ecore::EIntegerObject:
	//	'-'? INT
	public EIntegerObjectElements getEIntegerObjectAccess() {
		return pEIntegerObject;
	}
	
	public ParserRule getEIntegerObjectRule() {
		return getEIntegerObjectAccess().getRule();
	}
	
	//enum TypeOfPerson:
	//	BIOLOGICAL | ADOPTED | SEMIADOPTED | MARRIED | DISOWNED | ILLEGITIMATE;
	public TypeOfPersonElements getTypeOfPersonAccess() {
		return eTypeOfPerson;
	}
	
	public EnumRule getTypeOfPersonRule() {
		return getTypeOfPersonAccess().getRule();
	}
	
	//enum Gender:
	//	MALE | FEMALE | BIGENDER;
	public GenderElements getGenderAccess() {
		return eGender;
	}
	
	public EnumRule getGenderRule() {
		return getGenderAccess().getRule();
	}
	
	//Marriage:
	//	{Marriage}
	//	'Marriage'
	//	'{' ('type' type=TypeOfIntimateRelationship)? ('spouses' '(' spouses+=[Person|EString] (","
	//	spouses+=[Person|EString])* ')')? ('fromDate' fromDate=DateX)? ('toDate' toDate=DateX)? ('children' '{'
	//	children+=Person ("," children+=Person)* '}')?
	//	'}';
	public MarriageElements getMarriageAccess() {
		return pMarriage;
	}
	
	public ParserRule getMarriageRule() {
		return getMarriageAccess().getRule();
	}
	
	//Cohabitation:
	//	{Cohabitation} legitimate?='legitimate'?
	//	'Cohabitation'
	//	'{' ('type' type=TypeOfIntimateRelationship)? ('partners' '(' partners+=[Person|EString] (","
	//	partners+=[Person|EString])* ')')? ('children' '{' children+=Person ("," children+=Person)* '}')?
	//	'}';
	public CohabitationElements getCohabitationAccess() {
		return pCohabitation;
	}
	
	public ParserRule getCohabitationRule() {
		return getCohabitationAccess().getRule();
	}
	
	//PersonHistory:
	//	{PersonHistory}
	//	'PersonHistory'
	//	'{' ('gender' gender=Gender)? ('givenName' givenName=EString)? ('changed' changed=EDate)?
	//	'}';
	public PersonHistoryElements getPersonHistoryAccess() {
		return pPersonHistory;
	}
	
	public ParserRule getPersonHistoryRule() {
		return getPersonHistoryAccess().getRule();
	}
	
	//EBoolean ecore::EBoolean:
	//	'true' | 'false'
	public EBooleanElements getEBooleanAccess() {
		return pEBoolean;
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}
	
	//enum TypeOfIntimateRelationship:
	//	MONOGAMY | POLYGAMY | POLYFIDELITY;
	public TypeOfIntimateRelationshipElements getTypeOfIntimateRelationshipAccess() {
		return eTypeOfIntimateRelationship;
	}
	
	public EnumRule getTypeOfIntimateRelationshipRule() {
		return getTypeOfIntimateRelationshipAccess().getRule();
	}
	
	//EDate ecore::EDate:
	//	'EDate'
	public EDateElements getEDateAccess() {
		return pEDate;
	}
	
	public ParserRule getEDateRule() {
		return getEDateAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/ *'->'* /';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
