/*
 * generated by Xtext 2.10.0
 */
package org.xtext.genDSL2.gsl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.genDSL2.gsl.ui.internal.GslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class GslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return GslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return GslActivator.getInstance().getInjector(GslActivator.ORG_XTEXT_GENDSL2_GSL_GSL);
	}
	
}
