/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.gendsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.example.gendsl.ui.AbstractGenDslUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class GenDslUiModule extends AbstractGenDslUiModule {
  public GenDslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
