/*
 * generated by Xtext 2.10.0
 */
package org.xtext.genDSL2.gsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class GslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/genDSL2/gsl/parser/antlr/internal/InternalGsl.tokens");
	}
}
