/**
 * generated by Xtext 2.10.0
 */
package org.xtext.genDSL2.gsl.validation;

import org.xtext.genDSL2.gsl.validation.AbstractGslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class GslValidator extends AbstractGslValidator {
}
