/**
 * generated by Xtext 2.10.0
 */
package org.xtext.genDSL2.gsl.tests;

import com.google.inject.Inject;
import genDSL2.GenealogyTree;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.junit4.InjectWith;
import org.eclipse.xtext.junit4.XtextRunner;
import org.eclipse.xtext.junit4.util.ParseHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.xtext.genDSL2.gsl.tests.GslInjectorProvider;

@RunWith(XtextRunner.class)
@InjectWith(GslInjectorProvider.class)
@SuppressWarnings("all")
public class GslParsingTest {
  @Inject
  private ParseHelper<GenealogyTree> parseHelper;
  
  @Test
  public void loadModel() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("Hello Xtext!");
      _builder.newLine();
      final GenealogyTree result = this.parseHelper.parse(_builder);
      Assert.assertNotNull(result);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
