/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.gendsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class GenDslStandaloneSetup extends GenDslStandaloneSetupGenerated {

	def static void doSetup() {
		new GenDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
