/*
 * generated by Xtext 2.10.0
 */
package org.xtext.genDSL2.gsl

import org.xtext.genDSL2.gsl.valueconverter.GSLValueConverter

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class GslRuntimeModule extends AbstractGslRuntimeModule {
  override bindIQualifiedNameProvider() {
    GenDslQNP;
  }
  
  override bindIValueConverterService() {
    GSLValueConverter;
  }
  
}
