/**
 * generated by Xtext 2.10.0
 */
package org.xtext.genDSL2.gsl;

import org.eclipse.xtext.naming.IQualifiedNameProvider;
import org.xtext.genDSL2.gsl.AbstractGslRuntimeModule;
import org.xtext.genDSL2.gsl.GenDslQNP;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class GslRuntimeModule extends AbstractGslRuntimeModule {
  @Override
  public Class<? extends IQualifiedNameProvider> bindIQualifiedNameProvider() {
    return GenDslQNP.class;
  }
}
