/**
 * generated by Xtext 2.10.0
 */
package org.xtext.genDSL2.gsl;

import org.xtext.genDSL2.gsl.GslStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class GslStandaloneSetup extends GslStandaloneSetupGenerated {
  public static void doSetup() {
    GslStandaloneSetup _gslStandaloneSetup = new GslStandaloneSetup();
    _gslStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
